MAX_LINK_NUM_OF_CONTENT = 2
MAX_SIZE_OF_CONTENT = MAX_LINK_NUM_OF_CONTENT * 150
VERIFICATION_PERCENT = 20

def set_MAX_LINK_NUM_OF_CONTENT(_:int):
    MAX_LINK_NUM_OF_CONTENT = _
    MAX_SIZE_OF_CONTENT = MAX_LINK_NUM_OF_CONTENT * 150